// Automatically generated by Slang Reflector utility. DO NOT EDIT.
package voxel_shader

CameraUniforms :: struct #align(16) {
	viewProj: [4][4]f32, // offset: 0, size: 64
	position: [3]f32, // offset: 64, size: 12
}

VoxelVolume :: struct #align(16) {
	size: [3]u32, // offset: 0, size: 12
}

// --- VOXEL Pipeline Constants ---
VOXEL_CS_MAIN_ENTRY_POINT :: "cs_main"
VOXEL_THREAD_X :: 8
VOXEL_THREAD_Y :: 8
VOXEL_THREAD_Z :: 1
VOXEL_UNIFORM_BUFFER_SIZE :: 96
VOXEL_BINDING_G_VOLUME :: 1
VOXEL_BINDING_DATA :: 0
