// Automatically generated by Slang Reflector utility. DO NOT EDIT.
package ui_shader_shader

// --- UI_SHADER Pipeline Constants ---
UI_SHADER_VS_MAIN_ENTRY_POINT :: "vs_main"
UI_SHADER_FS_MAIN_ENTRY_POINT :: "fs_main"
