package utils

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"


entry_point :: struct {
	name:              string,
	thread_group_size: Maybe([3]int),
}

// Converts Slang JSON types to literal Odin types
get_odin_type :: proc(type_obj: json.Object) -> string {
	kind := type_obj["kind"].(json.String)

	switch kind {
	case "scalar":
		scalar_type := type_obj["scalarType"].(json.String)
		switch scalar_type {
		case "float32":
			return "f32"
		case "uint32":
			return "u32"
		case "int32":
			return "i32"
		}
	case "vector":
		count := int(type_obj["elementCount"].(json.Float))
		elem := type_obj["elementType"].(json.Object)
		elem_str := get_odin_type(elem)
		return fmt.tprintf("[%d]%s", count, elem_str)
	case "matrix":
		rows := int(type_obj["rowCount"].(json.Float))
		cols := int(type_obj["columnCount"].(json.Float))
		elem := type_obj["elementType"].(json.Object)
		elem_str := get_odin_type(elem)
		// Slang uses row-major layouts matching HLSL matrix representations
		return fmt.tprintf("matrix[%d,%d]%s", rows, cols, elem_str)
	}
	return "rawptr"
}

generate_shader_bindings :: proc(json_path: string, output_name: string, package_name: string) {
	data, ok := os.read_entire_file_from_path(json_path, allocator = context.allocator)
	if ok != nil {
		fmt.eprintln("Failed to read reflection file:", json_path)
		return
	}
	defer delete(data)

	json_value, err := json.parse(data)
	if err != .None {
		fmt.eprintln("Failed to parse reflection JSON:", err)
		return
	}
	defer json.destroy_value(json_value)

	root_obj := json_value.(json.Object)

	// Set up a dynamic string builder to write our generated file contents
	sb: strings.Builder
	strings.builder_init(&sb)
	defer strings.builder_destroy(&sb)

	// Extract shader base name from file path for unique naming tokens
	base_name := filepath.short_stem(json_path)
	prefix := strings.to_upper(base_name)

	// 1. Generate Header Boilerplate
	fmt.sbprintf(&sb, "// Automatically generated by Slang Reflector utility. DO NOT EDIT.\n")
	fmt.sbprintf(&sb, "package %s\n\n", package_name)

	// Keep track of binding indexes to generate constants at the end
	entry_points: [dynamic]entry_point
	uniform_buffer_size := 0

	// Create tracking dynamics to hold descriptor slots
	descriptor_slots := make([dynamic]struct {
			name: string,
			slot: int,
		}, 0, context.temp_allocator)

	// 2. Parse out Struct Formats
	if params_val, exists := root_obj["parameters"]; exists {
		for p_val in params_val.(json.Array) {
			p := p_val.(json.Object)
			param_name := p["name"].(json.String)
			type_obj := p["type"].(json.Object)

			// Process tracking uniform tracking block footprint
			if binding_val, b_exists := p["binding"]; b_exists {
				b := binding_val.(json.Object)
				if b["kind"].(json.String) == "uniform" {
					size := int(b["size"].(json.Float))
					offset := int(b["offset"].(json.Float))
					if offset + size > uniform_buffer_size {
						uniform_buffer_size = offset + size
					}
				}
				if b["kind"].(json.String) == "descriptorTableSlot" {
					slot := int(b["index"].(json.Float))
					append(&descriptor_slots, struct {
						name: string,
						slot: int,
					}{param_name, slot})
				}
			}
			if bindings_val, bs_exists := p["bindings"]; bs_exists {
				for b_val in bindings_val.(json.Array) {
					b := b_val.(json.Object)
					if b["kind"].(json.String) == "uniform" {
						size := int(b["size"].(json.Float))
						offset := int(b["offset"].(json.Float))
						if offset + size > uniform_buffer_size {
							uniform_buffer_size = offset + size
						}
					}
					if b["kind"].(json.String) == "descriptorTableSlot" {
						slot := int(b["index"].(json.Float))
						append(&descriptor_slots, struct {
							name: string,
							slot: int,
						}{param_name, slot})
					}
				}
			}

			// Generate struct templates for type definitions
			if type_obj["kind"].(json.String) == "struct" {
				struct_name := type_obj["name"].(json.String)
				fmt.sbprintf(&sb, "%s :: struct #align(16)", struct_name)
				strings.write_string(&sb, " {\n")

				if fields_val, f_exists := type_obj["fields"]; f_exists {
					current_offset := 0

					for f_val in fields_val.(json.Array) {
						f := f_val.(json.Object)
						f_name := f["name"].(json.String)
						f_binding := f["binding"].(json.Object)
						f_kind := f_binding["kind"].(json.String)
						f_type := f["type"].(json.Object)

						if f_kind == "uniform" {
							offset := int(f_binding["offset"].(json.Float))
							size := int(f_binding["size"].(json.Float))

							// Handle dynamic hardware padding explicitly to keep layouts solid
							if offset > current_offset {
								fmt.sbprintf(
									&sb,
									"\t_pad_%d: [%d]u8,\n",
									offset,
									offset - current_offset,
								)
							}

							type_str := get_odin_type(f_type)
							fmt.sbprintf(
								&sb,
								"\t%s: %s, // offset: %d, size: %d\n",
								f_name,
								type_str,
								offset,
								size,
							)
							current_offset = offset + size
						} else if f_kind == "descriptorTableSlot" {
							slot := int(f_binding["index"].(json.Float))
							append(&descriptor_slots, struct {
								name: string,
								slot: int,
							}{f_name, slot})
						}
					}
				}
				fmt.sbprintf(&sb, "}\n\n")
			}
		}
	}

	// 3. Process thread bounds parameters
	if entry_points_val, exists := root_obj["entryPoints"]; exists {
		for entry_val in entry_points_val.(json.Array) {
			entry := entry_val.(json.Object)
			entry_point := entry_point {
				name = entry["name"].(json.String),
			}
			fmt.println("Processing entry point:", entry["name"].(json.String))
			if group_size_val, gs_exists := entry["threadGroupSize"]; gs_exists {
				gs_arr := group_size_val.(json.Array)
				entry_point.thread_group_size = [3]int {
					int(gs_arr[0].(json.Float)),
					int(gs_arr[1].(json.Float)),
					int(gs_arr[2].(json.Float)),
				}
			}


			append(&entry_points, entry_point)
		}
	}

	// 4. Output the Metadata Constants block
	fmt.sbprintf(&sb, "// --- %s Pipeline Constants ---\n", prefix)
	for entries in entry_points {
		fmt.sbprintf(
			&sb,
			"%s_ENTRY_POINT :: \"%s\"\n",
			strings.join({prefix, strings.to_upper(entries.name)}, "_"),
			entries.name,
		)
		if entries.thread_group_size != nil {
			fmt.sbprintf(&sb, "%s_THREAD_X :: %d\n", prefix, entries.thread_group_size.([3]int)[0])
			fmt.sbprintf(&sb, "%s_THREAD_Y :: %d\n", prefix, entries.thread_group_size.([3]int)[1])
			fmt.sbprintf(&sb, "%s_THREAD_Z :: %d\n", prefix, entries.thread_group_size.([3]int)[2])
		}

	}
	if uniform_buffer_size > 0 {
		fmt.sbprintf(&sb, "%s_UNIFORM_BUFFER_SIZE :: %d\n", prefix, uniform_buffer_size)
	}

	for slot in descriptor_slots {
		fmt.printfln("Adding descriptor slot for %s: %d", slot.name, slot.slot)
		fmt.sbprintf(&sb, "%s_BINDING_%s :: %d\n", prefix, strings.to_upper(slot.name), slot.slot)
	}
	output_directory := fmt.tprintf("src/shaders/%s", package_name)

	// Write the resulting generated code file out cleanly to disk
	if !os.is_dir(output_directory) && os.make_directory_all(output_directory) != nil {
		fmt.eprintln("Failed to create output directory for shader bindings")
		return
	}
	output_odin_path, alloc_err := filepath.join(
		{output_directory, strings.join({output_name, ".odin"}, "")},
		allocator = context.allocator,
	)
	fmt.println("outputing to:", output_odin_path)
	defer delete(output_odin_path)
	write_err := os.write_entire_file(output_odin_path, data = strings.to_string(sb))
	fmt.println("write err:", write_err)
	// if os.write_entire_file(output_odin_path, data = transmute([]u8)strings.to_string(sb)) != nil {
	// 	fmt.eprintln("Failed to write output file:", output_odin_path)
	//
	// }
}

main :: proc() {
	// Simple command line interface execution execution entry point
	// Compile shaders and then generate bindings for them

	compile("shader_src/", "shaders/")
	iter, err := os.read_all_directory_by_path("shaders/", context.allocator)
	if err != nil {
		fmt.eprintln("Failed to read shaders directory for binding generation:", err)
		return
	}
	for file, _ in iter {
		if os.is_dir(file.fullpath) {
			continue
		}
		if filepath.ext(file.name) == ".json" {
			base_name := filepath.short_stem(file.name)
			package_name := strings.to_lower(base_name)
			output_name := strings.join({base_name, "_shader"}, "")
			generate_shader_bindings(
				fmt.tprintf("shaders/%s.json", base_name),
				package_name,
				output_name,
			)
		}
	}
	fmt.println("Successfully generated bindings!")
}
