// Automatically generated by Slang Reflector utility. DO NOT EDIT.
package post_processing_shader

// --- POST_PROCESSING Pipeline Constants ---
POST_PROCESSING_MAIN_ENTRY_POINT :: "main"
POST_PROCESSING_THREAD_X :: 8
POST_PROCESSING_THREAD_Y :: 8
POST_PROCESSING_THREAD_Z :: 1
